import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Providers from "./core/providers";

const kanit = Kanit({
  weight: "400",
  subsets: ["thai", "vietnamese", "latin"],
});

export const metadata: Metadata = {
  title: "Mackerel Fish Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <Navbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
